[project]
authors = [
  {author = "seriaati", email = "seria.ati@gmail.com"},
]
dependencies = [
  "aiofiles>=24.1.0",
  "aiohttp-client-cache[sqlite]>=0.11.0",
  "discord-py[speed]>=2.4.0",
  "jishaku>=2.5.2",
  "python-dotenv>=1.0.1",
  "pyyaml>=6.0.2",
  "tortoise-orm[asyncpg]>=0.21.6",
  "seria-library>=1.5.4",
  "uvloop>=0.20.0; platform_system == 'Linux'",
]
description = "Discord bot that fixes social media embeds"
license = "GPL-3.0-only"
name = "embed-fixer"
readme = "README.md"
requires-python = ">=3.11"
version = "1.2.4"

[tool.uv]
dev-dependencies = [
  "ruff>=0.6.2",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["embed_fixer"]
